### PR TITLE
Changes on feedback/tip 

### PR DESCRIPTION
**Pull request by francisfueconcillo**

### CODE REVIEW

**Comment by francisfueconcillo** [comment]
This is to fix http://h5p.org/node/1851

**Comment by falcon-git** [comment]
Thank you for contributing. 

I think we should just remove the button for displaying the feedback and display it directly. Also I think the way we display it should be redesigned - we should display it below the alternative and not on top of the below alternative. What do you think about this?

(I'm sorry about the late reply)

**Comment by haleyagentic** [comment]
Hello,

francisfueconcillo submitted this pull request at our request. Your comments on how it should be redesigned sound good. Are are you saying you will be making those changes?

**Comment by falcon-git** [comment]
The community should do it. I don't know of anyone else working on this at the moment. The H5P Team isn't working on it.

**Comment by francisfueconcillo** [comment]
Changes done.  Feedback /Tip text is appended next to answers option. Thought bubble icon removed.

**Comment by thomasmars** [comment]
Thank you for your contribution, I have merged the commit into master.

**Pull request merged**
