### PR TITLE
add hanging indent to answer text

### PR DESCRIPTION
**Pull request by otacke**
If an answer's text needed more than one line, the lower lines didn't align with line one. With this tiny change they do, and I think this looks much nicer.

### CODE REVIEW

**Comment by falcon-git** [comment]
Great, I see what you mean. Have made an issue in our Jira(which will be made public as soon as we get around to it) about testing this fix in all browsers with multiple lines and paragraphs, but I would think that this works fine!

**Comment by otacke** [comment]
Sounds great!

**Comment by thomasmars** [comment]
Looks good, and works great! :)
Can you bake the 2em left padding of .h5p-alternative-container into the already-existing padding rule? Also the 2em padding-left for the .h5p-alternative-container:before could be baked into the "left" rule, by adding 2em to it.

**Comment by otacke** [comment]
I'll look into it tonight.

**Comment by otacke** [comment]
done

**Comment by thomasmars** [comment]
Excellent, thanks!

**Pull request merged**
