### PR TITLE
Strip html tags from definition and response

### PR DESCRIPTION
**Pull request by garemoko**
Addresses https://github.com/h5p/h5p-multi-choice/issues/5

### CODE REVIEW

**Comment by garemoko** [comment]
I've tested this with the Question Set example and it successfully strips out the div tags.

**Comment by phalancs** [comment]
I would love to use some HTML within the response fields (right or wrong follow up texts). How can we activate this?

**Comment by garemoko** [comment]
@phalancs html in these fields is not valid xapi. 

What's your use case? maybe I can suggest an alternative?

**Comment by phalancs** [comment]
@garemoko Thanks for your reply. We want to implement a simpel lionk wiothin the response fields, but any html seems te get stripped. :(

**Pull request merged**
